import { VMConnection, AuditLog, SecurityPolicy, CloudBackupState, AdminStats } from './types';

export const INITIAL_CONNECTIONS: VMConnection[] = [
  {
    id: 'vm-1',
    name: 'Windows Server 2022',
    host: '192.168.1.45',
    port: 3389,
    protocol: 'RDP',
    rdpVersion: 'RDP 10.11 (Win11/Server 2022)',
    engineProfile: 'Chromium 128 (Hardware Accelerated + WebGL)',
    status: 'live',
    latencyMs: 12,
    encryptionSuite: 'AES-256-GCM • TLS 1.3',
    e2eeFingerprint: 'SHA256:7B:4E:91:A3:F8:0D:2C:19',
    mfaRequired: true,
    osType: 'windows',
    username: 'Administrator',
    description: 'Máy chủ Active Directory & Dịch vụ Remote Desktop trung tâm',
    lastConnected: 'Đang hoạt động',
  },
  {
    id: 'vm-2',
    name: 'Ubuntu Dev Cluster',
    host: 'cluster-04.internal.io',
    port: 5901,
    protocol: 'VNC',
    vncVersion: 'RFB 3.8 (TLS 1.3 / VeNCrypt)',
    engineProfile: 'Chromium 128 (Hardware Accelerated + WebGL)',
    status: 'idle',
    latencyMs: 24,
    encryptionSuite: 'ChaCha20-Poly1305 • TLS 1.3',
    e2eeFingerprint: 'SHA256:3F:8A:22:9B:C1:44:8D:6E',
    mfaRequired: true,
    osType: 'ubuntu',
    username: 'devops-root',
    description: 'Cụm Kubernetes development & Docker container node',
    lastConnected: '4 phút trước',
  },
  {
    id: 'vm-3',
    name: 'Kali SecOps Lab',
    host: '10.240.12.8',
    port: 5900,
    protocol: 'VNC',
    vncVersion: 'TightVNC 2.8 (Lossless Compression)',
    engineProfile: 'Chromium 114 (Standard WebSocket Offscreen)',
    status: 'live',
    latencyMs: 18,
    encryptionSuite: 'AES-256-GCM • Double Ratchet E2EE',
    e2eeFingerprint: 'SHA256:99:A1:66:B4:7C:E0:21:55',
    mfaRequired: true,
    osType: 'kali',
    username: 'pentest-analyst',
    description: 'Môi trường kiểm thử an toàn mạng cô lập Air-gapped',
    lastConnected: 'Đang hoạt động',
  },
  {
    id: 'vm-4',
    name: 'macOS Sequoia Build Node',
    host: 'build-node-02.corp',
    port: 5900,
    protocol: 'VNC',
    vncVersion: 'RFB 3.8 (TLS 1.3 / VeNCrypt)',
    engineProfile: 'Chromium 128 (Hardware Accelerated + WebGL)',
    status: 'idle',
    latencyMs: 31,
    encryptionSuite: 'AES-128-GCM • TLS 1.3',
    e2eeFingerprint: 'SHA256:5D:1E:83:A0:72:6B:49:FE',
    mfaRequired: false,
    osType: 'macos',
    username: 'builder-ci',
    description: 'Máy ảo biên dịch iOS / macOS CI/CD Runner',
    lastConnected: '18 phút trước',
  },
  {
    id: 'vm-5',
    name: 'Debian 12 MicroVM Gateway',
    host: '172.16.88.2',
    port: 3389,
    protocol: 'RDP',
    rdpVersion: 'RDP 10.4 (Win10/Server 2019)',
    engineProfile: 'Chromium Legacy (Low Bandwidth Compat)',
    status: 'live',
    latencyMs: 9,
    encryptionSuite: 'AES-256-GCM • WireGuard Tunnel',
    e2eeFingerprint: 'SHA256:88:BB:11:4A:69:CF:90:3A',
    mfaRequired: true,
    osType: 'debian',
    username: 'sysadmin',
    description: 'Cổng điều hướng phân tán & Reverse proxy Guacamole',
    lastConnected: 'Đang hoạt động',
  }
];

export const INITIAL_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: 'Vừa xong (10:48:12)',
    event: 'Xác thực MFA thành công',
    severity: 'success',
    user: 'admin@corp.internal',
    ipAddress: '192.168.1.102',
    details: 'TOTP Token hợp lệ cho phiên Windows Server 2022 (RDP 10.11)',
    e2eeValidated: true,
  },
  {
    id: 'log-2',
    timestamp: '2 phút trước',
    event: 'Đồng bộ sao lưu đám mây',
    severity: 'info',
    user: 'System Worker',
    ipAddress: '127.0.0.1',
    details: 'Đã mã hóa và đồng bộ 5 cấu hình máy ảo lên Encrypted Vault (Rev #14)',
    e2eeValidated: true,
  },
  {
    id: 'log-3',
    timestamp: '5 phút trước',
    event: 'Khởi tạo kênh E2EE Handshake',
    severity: 'info',
    user: 'devops-root',
    ipAddress: '10.240.12.8',
    details: 'Khóa đối xứng Ephemeral ECDH X25519 được xác thực an toàn',
    e2eeValidated: true,
  },
  {
    id: 'log-4',
    timestamp: '14 phút trước',
    event: 'Cảnh báo chính sách bảo mật',
    severity: 'warning',
    user: 'guest_operator',
    ipAddress: '172.20.10.4',
    details: 'Đã chặn nỗ lực sao chép clipboard từ Kali SecOps Lab ra ngoài thiết bị',
    e2eeValidated: true,
  }
];

export const INITIAL_POLICY: SecurityPolicy = {
  enforceMfaForAll: true,
  enforceTls13E2ee: true,
  blockClipboardExport: false,
  autoIdleTimeoutMinutes: 15,
  sessionRecordingAudit: true,
  maxConcurrentSessions: 5,
  allowGuestAccess: false,
};

export const INITIAL_BACKUP: CloudBackupState = {
  isSyncing: false,
  lastBackupTime: '2 phút trước',
  backupVaultSize: '1.42 MB (Đã nén & Mã hóa AES-256)',
  backupRevisions: 14,
  autoSync: true,
  provider: 'Encrypted Cloud Storage',
  syncedDevices: [
    {
      id: 'dev-1',
      name: 'Android Workstation (Thiết bị này)',
      platform: 'Android 14 / Chromium WebView 128',
      lastSeen: 'Đang trực tuyến',
      isCurrent: true,
    },
    {
      id: 'dev-2',
      name: 'SecOps ThinkPad X1',
      platform: 'Chromium Enterprise v128 / Linux',
      lastSeen: '12 phút trước',
      isCurrent: false,
    },
    {
      id: 'dev-3',
      name: 'iPad Pro 12.9 M2',
      platform: 'WebKit WebApp PWA',
      lastSeen: 'Hôm qua',
      isCurrent: false,
    },
  ],
};

export const INITIAL_STATS: AdminStats = {
  totalUsers: 24,
  activeConnections: 3,
  totalVMs: 5,
  complianceScore: 98,
  threatLevel: 'Low',
  e2eeBandwidthMbps: 48.6,
};
